-- phpMyAdmin SQL Dump
-- version 4.9.5
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jan 08, 2021 at 03:45 AM
-- Server version: 10.3.18-MariaDB
-- PHP Version: 7.3.23

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `id15849605_cdhd`
--

-- --------------------------------------------------------

--
-- Table structure for table `glimpse`
--

CREATE TABLE `glimpse` (
  `id` int(10) UNSIGNED NOT NULL,
  `title` varchar(15) COLLATE utf8_unicode_ci NOT NULL,
  `glimpse_date` varchar(15) COLLATE utf8_unicode_ci NOT NULL,
  `heading` text COLLATE utf8_unicode_ci NOT NULL,
  `content` text COLLATE utf8_unicode_ci NOT NULL,
  `prayer_focus` text COLLATE utf8_unicode_ci NOT NULL,
  `featured_verse` text COLLATE utf8_unicode_ci NOT NULL,
  `featured_quote` text COLLATE utf8_unicode_ci NOT NULL,
  `image_link` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `type` int(11) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `transition` text COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `glimpse`
--

INSERT INTO `glimpse` (`id`, `title`, `glimpse_date`, `heading`, `content`, `prayer_focus`, `featured_verse`, `featured_quote`, `image_link`, `type`, `created_at`, `transition`) VALUES
(63, '2021-01-05', '2021-01-05', 'On the Beginning of the Construction of the Golden Gate Bridge the USA', 'In 1933, the golden gate bridge construction begun.<br/><br/>\r\n\r\nThis was after workers started excavating 3.25 million cubic feet of dirt for the structure\'s big anchorage.  The plan to build the bridge that would connect the San Francisco Peninsula with the southern end of Marin country begun in 1849 after the Gold rush in the land north of San Francisco.<br/><br/>\r\n\r\nCity engineer <i>Michael O\'Shaughnessy</i> who also named the gate, and <i>Joseph Strauss</i>, another engineer and poet, took charge of the construction that cost around US $30 million and took four years to finish.<br/><br/>\r\n\r\nIt officially opened on <i>May 27, 1937</i> eventually becoming a world famous American landmark and tourist spot.\r\n', 'May the <i>Golden Gate Bridge</i> and all the other (major) bridges the world over be properly maintained and enhanced to survive massive earthquakes and flooding. <br/><br/>\r\n\r\nMay more vital bridges be built where strategic and truly needed.', 'Jesus answered, <i>\"I am the way the truth and the life. No one comes to the father except through me.\"</i><br/>\r\n- <b>John 14.6</b>', '<i>In human history, we can see sparkles of God\'s redeeming stories</i><br/>\r\n- Pastor Jose Tacadena', 'https://www.history.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTY1MTc3MjE0MzExMDgxNTQ1/topic-golden-gate-bridge-gettyimages-177770941.jpg', 0, NULL, 'While human bridges are mostly helpful for connecting locations and people, the spiritual bridge who is the Lord Jesus is certainly millions better on all fronts. We must appreciate the Lord Jesus connecting us to God the father.<br/><br/>'),
(64, '2021-01-05', '2021-01-05', 'In 2011, Senator Antonio Trillanes IV and 18 other Magdalo Officers formally applied for Amnesty.', 'Senator Antonio Trillanes IV and other members of the Magdalo group pose for a <i>Group Shot</i> after applying for government amnesty before the Department of National Defense amnesty committee at <i>Camp Aguinaldo</i>.<br/><br/>\r\n\r\nThey sent their application to the <i>Department of National Defense (DND) Ad Hoc Committee</i> in <i>Camp Aguinaldo, Quezon City.</i><br/><br/>\r\n\r\nTrillanes was one of the leaders of the 2003 Oakwoood Mutiny where they lmabdasted the supposed corruption of the President Gloria Arroyo Administration. <br/><br/>\r\n\r\nIn 2007, he walked out of the Camp Crame Custodial Center after the Makti Regional Trial Court and staged the Manila Peninsula Hotel Siege.<br/><br/>\r\n\r\nIn December 2010, he was given provisional liberty, and a year later was given amnesty by then President Noynoy Aquino. <br/><br/>', 'May God\'s truth, fairness, and justice prevail in Senator Trillanes\' pending case by the Department of Justice. May every government refrain from using their power to unjustly harass their critics.', '<i>\"And that is what some of you were. \r\nBut you were washed, you were sanctified, you were justified in the name of the Lord Jesus Christ and the Spirit of our God.\"</i><br>\r\n- <b>Romans 8:1</b>', '<i>\"In human history, we can see sparkles of God\'s redeeming stories\"</i>\r\n- Pastor Jose Tacadena', 'https://www8.gmanews.tv/webpics/infotech/trillanesamnesty1.jpg', 1, NULL, 'While government amnesty may be considered a great blessing to those who receive it, how much more should God\'s own version of Amnesty? The Bible calls it justification and is given to those who receive Jesus as their personal and Lord and Savior.  We must strive to reciprocate God justifying us by living for him. <br/>'),
(69, '2021-01-06', '2021-01-06', 'In 1812, <i>Melchora Aquino de Ramos,</i> known as <i>Tandang Sora,</i> was born in Balintawak.', 'Even while already 84 years old, she opened her house to the Katipuneros led by <i>Andres Bonifacio</i>. She provided the revolutionaries food, clothing and shelter. Because of this, she was arrested by Guardia Civil in Barrio Pasong Putik, Novaliches and gailed in Bilibid Prison in Manila. She was even exiled to Guam where she lived as a servant. She came back to the Philippines in 1903, at 91 years old, and died at 107 in 1919.', 'May we not forget her heroism as well as those who have sacrificed for the freedom of the Philippines against tyrants. May we continue to respect the elderlies and give them enough space to continue experiencing self actualization and to bless other people through their talents, skills and experience and passion.', 'Many women were there, watching from a distance. They had followed Jesus from Galilee to care for his needs. Among them were Mary Magdalene, Mary the mother of James and Joseph, and the mother of Zebedee\'s sons.<br/>\r\n- Matthew 27:55-56', 'In human history, we can see sparkles of God\'s redeeming stories.<br/>\r\n- Pastor Jose Tacadena', 'https://kahimyang.com/resources/tandang_sora.webp', 1, NULL, 'Do you know that even our dear Lord Jesus Christ and his apostles were ministered by numerous women of various ages and background? We must strive to respect and appreciate the women in our society.'),
(68, '2021-01-06', '2021-01-06', 'In 1838, <i>Samuel Morse\'s</i> telegraph system was demonstrated in public for the first time.<br/><br/>', 'This happened at the <i>Speedwell Iron Works</i> in <i>Morristown, New Jersey.</i>  His device used electric impulses to transmit encoded messages over a wire.<br/><br/>\r\nIn 1843, he convinced the US Congress to fund the construction of the first telegraph line in the country - from <i>Washington, DC to Baltimore.</i> In 1844, the Massachusetts-born Morse sent his first official telegram over the line. His message, <b>\"What hat God wrought!\"</b>', 'May telegraph and the more modern means of communication, especially the internet, be developed further, and be more accessible even to the third world countries and marginalized people.', '\"Now to him who is able to do immeasurably more than all we ask or imaging, according to his power that is at work within us, to him be glory in the church and in Christ Jesus throughout all generations, for ever and ever! Amen.\"<br/>\r\n- Ephesians 3:20-21', '\"In human history, we can see sparkles of God\'s redeeming stories\"<br/>\r\n- Pastor Jose Tacadena', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTepj4E0HfrDPWrhFYaIk-BqeRtuJUS3BtKdQ&usqp=CAU', 0, NULL, 'It\'s heartwarming that Morse attributed his great invention in part to God\'s working through his ability and knowledge. More than the telegraph, God not only receives but amplifies our communication to the point of blessing us beyond our abilities, good intentions and passion. So, he deserves our praise for our every achievement. We must strive to honor God for every enabling He has given us to achieve in life.'),
(70, '2021-01-07', '2021-01-07', 'In 1789, the first presidential election in the United States of America was held.', 'Only white men who owned property were allowed to vote. Early favorite George Washington won the election unanimously as all 69 electors chose him. John Adams won as the first vice president.<br/><br/>\r\nHe was sworn as the first president of the USA on April 30, 1789. He was later unanimously re-elected in 1792 for another term and ended his tenure on March 7, 1797.', 'May the USA continue to be a model of democracy and fair elections.<br/>\r\nMay the citizens be wiser in electing their national leaders. While the election candidates be more qualified and responsible to the position they are vying for.', 'Therefore, my brothers and sisters, make every effort to confirm your calling and election. For if you do these things, you will never stumble.<br/>\r\n- <b>2 Peter 1:10</b><br/><br/>\r\n\r\nYou did not choose me, but I chose you and appointed you so that you might go and bear fruit - fruit that will last.<br/>\r\n- <b>John 15:6</b>', 'In human history, we can see sparkles of God\'s redeeming stories.<br/>\r\n- Pastor Jose Tacadena', 'https://www.biography.com/.image/t_share/MTY2NDcwODAyODk0NDk2OTI5/gilbert_stuart_williamstown_portrait_of_george_washington_promo.jpg', 0, NULL, 'Do you know that in a way, the Lord Jesus Christ has elected Christians? We must strive to deserve somehow God choosing us to grow in our faith.'),
(71, '2021-01-07', '2021-01-07', 'In 1901, Major general Arthur MacArthur Jr. Ordered the deportation of leaders of the Philippine revolution against the USA to Guam.', 'MacArthur Jr. was the military Governor-General of the American occupied Philippines.<br/><br/>\r\nHe particularly detested Apolinario Mabini for leading the Filipino revolutionaries. Mabini was the chief adviser of Gen. Emilio Aguinaldo, who wrote the \"True Decalogue\" which inspired the Filipinos to fight and die for freedom.<br/><br/>\r\nMabini sailed to Guam along with 31 others including Pablo Ocampo, Pio del Pilar, and Gen. Artemio Ricarte.', 'May deportees be protected from all sorts of abuse by citizens of their host countries, while the former learn to adjust to the foreigners\' culture and be better qualified and equipped to return home. May God continue to bless our overseas Filipino workers everywhere.', 'When a foreigner resides among you in your land, do not mistreat them. The foreigner residing among you must be treated as your native born. Love them as yourself, for you were foreigners in Egypt. I am the Lord your God.<br/><br/>\r\n- Leviticus 19:33-34', 'In human history, we can see sparkles of God\'s redeeming stories.<br/>\r\n- Pastor Jose Tacadena', 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Arthur_MacArthur_Jr.jpg', 1, NULL, 'The reality of people being deported or voluntarily journeying abroad moved God to remind us to treat foreigners properly. We must strive to treat aliens and visitors well.'),
(72, '2021-01-08', '2021-01-08', 'On the death of Galileo Galilei, the father of modern astronomy and the father of modern physics.', 'In 1642, Italian astronomer Galileo Galilei died in Italy at 77 years old.<br/><br/>\r\nRecognized as the Father of Modern Astronomy and the Father of Modern Physics. Due to his revolutionary discoveries, Galileo was the first person to use the telescope to observe the skies. He discovered the moons of Jupiter, the rings of Saturn, sunspots and solar rotation.<br/><br/>\r\nHe later published his confirmation that the earth orbits the sun. For this, he was tried and found guilty by the inquisition (the legal body of the Catholic Church) of heresy and was sentenced to life imprisonment in 1633, (which was downgraded to lifetime house arrest).', 'May religious leaders do not reject truly scientific realities; and may scientist and other Science-based people do not ridicule spiritual realities.<br/><br/>\r\nMay more scientists discover and invent more truly useful things and realities.\r\nMay they become more open to the Creator', 'He who made the pleiades and orion, who turns midnight into dawnland darkens day into night, who calls for the waters of the sea and pours them out over the face of the land - The Lord is His name.<br/>\r\n- Amos 5:8', '', 'https://images.saymedia-content.com/.image/t_share/MTc1Nzg1MTc0NDUyMzQ3OTU5/galileo-galilei-discovers-the-moons-of-jupiter-and-the-phase-of-venus.jpg', 0, NULL, 'While we may be amazed at the wonderful creations above and beyond us - we must be cognizant of the Supreme One who made all of these.<br/>\r\nWe must strive to recognize that God, indeed created all natural creations.'),
(73, '2021-01-08', '2021-01-08', 'In 2016, then 82-year old German Molina Moreno, better known as Kuya Germs and the \"Master Showman\" died due to Cardiac arrest.', 'This Spanish-Filipino TV host, actor-comedian and talent manager was a former teen vendor and jeepney barker. He got into showbiz when he started to work as a janitor and curtain raiser at the Clover Leaf theater in 1957.<br/><br/>\r\nHe got his first break when he was chosen to portray the role of Jesus Christ for the Manila Grand Opera. He then became a comedian for Sampaguita Pictures, home of the biggest starts at that time.<br/><br/>\r\nHis biggest break came as a host of the Sunday noontime variety show, GMA Supershow in the late 1970s, and later as the host, star-builder and producer of \"That\'s Entertainment\", which discovered and developed the most famous stars in the Philippine entertainment industry then.', 'May more sincere and helpful star-builders and talent managers rise up at the Philippine Entertainment Industry. May sexual harassment, bullying and all the other forms of abuse be prevented in this industry.<br/><br/>\r\nMay those truly deserving artists be given the ample chance to be recognized.', 'We who are strong ought to bear with the failings of the weak and not to please ourselves. Each of us should please our neighbors for their good, to build them up.<br/><br/>\r\n- Romans 15:1-2', '', 'https://contents.pep.ph/images2/2018/10/04/kuya-germs-main.jpg', 1, NULL, 'Not only the talent managers, but everyone of us are commanded to be sincere in building up others, especially those who are weaker than us. We must strive to empathize and help those who are weak and in the need.');
(74, '2021-01-09', '2021-01-09', 'On The Unveiling Of The Iphone By Steve Jobs', 'In 2007, Steve Jobs unveiled the iPhone, the touch screen mobile phone with an iPod, camera and web-browsing features.<br/><br/>\r\n\r\nIn its unveiling that happened in MacWorld Convention in San Francisco, Jobs claimed that his revolutionary and magical products is literally five years ahead than any other phone. <br/><br/>\r\n\r\n In November, Time Magazine named the iPhone, which in ten months had sale of 1.4 million already, the<i>“Invention of the Year”</i>. <br/><br/>\r\n\r\n In 2012, more than 200 million phones had been sold, making the Apple which Jobs co-founded in 1976, into one of the Earth\'s most valuable corporations.\r\n', 'May more advanced and efficiently useful gadgets and equipment be invented at more affordable costs. May we all be good stewards of such tools and refrain from using them only for our own enjoyment.', 'We proclaim to you what we have seen and heard, so that you also may have fellowship with us. And our fellowship is with the Father and with his Son, Jesus Christ. <br/>\r\n- <b>1 John 1:3</b>', '<i>In human history, we can see sparkles of God\'s redeeming stories</i><br/>\r\n- Pastor Jose Tacadena','https://bit.ly/3nrJGXq', 0, NULL, 'While inventions like iPhones connect people faster and more conveniently, studies have shown that these actually devalue meaningful communications with them. We must go back to the basic of communication with God and others through fellowship  - having in-depth communication with them that lead to better and spiritual relationships. We must strive to help in fostering better communication and bonding with others.'),
(75, '2021-01-09', '2021-01-09', 'On The Establishment Of The Barter Trade Zone In Mindanao', 'In 1973, a barter trade zone was established in Mindanao. <br/><br/>\r\n\r\n This was through Presidential Decree No. 93, signed by then Pres. Ferdinand Marcos. It allowed businessmen from the Sulu Archipelago to trade with neighboring islands and sell imported items within the region without tariff duties. <br/><br/>\r\n\r\n In this way, the Filipinos can buy imported items, especially electronic gadgets and equipments at relatively low prices.', 'May the government\'s plan to revive the barter trade zone in Mindanao this year succeeded.', 'So in everything, do to others what you would have them do to you, for this sums up the Law and the Prophets.<br/>\r\n–<b>Matthew 7:12</b>', '<i>In human history, we can see sparkles of God\'s redeeming stories</i><br/>\r\n- Pastor Jose Tacadena', 'https://bit.ly/2LcKbaW', 1, NULL, 'There is a much better barter trade than economic goods. This is called by many as the Golden Rule. We must strive to apply God\'s Golden Rule.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `glimpse`
--
ALTER TABLE `glimpse`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `glimpse`
--
ALTER TABLE `glimpse`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=74;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
